/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencv_samples_tutorial4_NativePart */

#ifndef _Included_org_opencv_samples_tutorial4_NativePart
#define _Included_org_opencv_samples_tutorial4_NativePart
#ifdef __cplusplus
extern "C" {
#endif
#undef org_opencv_samples_tutorial4_NativePart_PROCESSING_MODE_NO_PROCESSING
#define org_opencv_samples_tutorial4_NativePart_PROCESSING_MODE_NO_PROCESSING 0L
#undef org_opencv_samples_tutorial4_NativePart_PROCESSING_MODE_CPU
#define org_opencv_samples_tutorial4_NativePart_PROCESSING_MODE_CPU 1L
#undef org_opencv_samples_tutorial4_NativePart_PROCESSING_MODE_OCL_DIRECT
#define org_opencv_samples_tutorial4_NativePart_PROCESSING_MODE_OCL_DIRECT 2L
#undef org_opencv_samples_tutorial4_NativePart_PROCESSING_MODE_OCL_OCV
#define org_opencv_samples_tutorial4_NativePart_PROCESSING_MODE_OCL_OCV 3L
/*
 * Class:     org_opencv_samples_tutorial4_NativePart
 * Method:    initCL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_opencv_samples_tutorial4_NativePart_initCL
  (JNIEnv *, jclass);

/*
 * Class:     org_opencv_samples_tutorial4_NativePart
 * Method:    closeCL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_opencv_samples_tutorial4_NativePart_closeCL
  (JNIEnv *, jclass);

/*
 * Class:     org_opencv_samples_tutorial4_NativePart
 * Method:    processFrame
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_opencv_samples_tutorial4_NativePart_processFrame
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
